homeassistant:
  name: Zuhause
  latitude: !secret HOMEASSISTANT_LATITUDE
  longitude: !secret HOMEASSISTANT_LONGITUDE
  elevation: 256
  unit_system: metric
  time_zone: Europe/Berlin
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - '/tmp'
  auth_providers:
     - type: homeassistant
     - type: trusted_networks
       trusted_networks:
         - 192.168.170.0/24
# Text to speech
tts:
  - platform: google_translate
    language: "de"
    
    
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
camera: !include camera.yaml


telegram_bot:
  - platform: polling
    api_key: !secret telegrambotapikey01
    allowed_chat_ids:
      - !secret telegramallowedchat_ids01

# Example configuration.yaml entry for the notifier
notify:
  - platform: telegram
    name: Telegram02
    chat_id: !secret telegramallowedchat_ids01

  # It is possible to add multiple notifiers by using another chat_id
  # the example belows shows an additional notifier which sends messages to the bot which is added to a group
  - platform: telegram
    name: Telegram01
    chat_id: !secret telegramallowedchat_ids01
    
light:
  - platform: flux_led
    automatic_add: true
    devices:
      192.168.170.33:
        name: Flur-Lichtstreifen
        mode: rgb
      192.168.170.27:
        name: Kueche-Lichtstreifen
      192.168.170.29:
        name: Schlafzimmer-Bild-Lichtstreifen
        mode: rgb
        
        
emulated_hue:
  host_ip: 192.168.170.42
  listen_port: 80
  advertise_ip: 192.168.170.42
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
  entities:
    light.yeelight_color_0x0000000003731644:
      name: "Arbeitszimmer Standlicht"
    light.yeelight_strip6_0x0000000015619634:
      name: "Schreibtisch"              
        
        
        
